version: '3.6'

services:

  testrunner:
    image: "${TAG}"
    depends_on:
      - eventstore
      - node1
      - node2
      - node3
    networks:
      app_net_tests:
        ipv4_address: 172.16.239.20
    environment:
        - abc=123
    volumes:
      - "${TESTRESULTS}:/testresults"
    command: ["dotnet", "test", "--logger:trx", "-v:normal", "--no-build", "--no-restore", "-c", "${CONFIGURATION}", "-r" , "/testresults" , "-d", "/testresults/diag.txt", "/p:NuGetVersionV2=${NUGETVERSIONV2}", "/p:AssemblySemVer=${ASSEMBLYSEMVER}" ]
